#SI notre prog de test retourn 1 : echec de la pipeline
#Ici on fait le makefile de notre projet
build-job:
  stage: build
  script:
    - cd src/Menus
    - make

test:
  stage: test
  script:
    #- make projet-pfr
    # - gcc testsCI/indexation.c -o testsCI/tests.out
    - cd testsCI
    - make
    - ./tests
