#SI notre prog de test retourn 1 : echec de la pipeline
#Ici on fait le makefile de notre projet
build-job:
  stage: build
  script:
    - cd src/Menus
    - make

tests:
  stage: tests
  script:
    - cd testsCI
    - make
    - ./tests

