#SI notre prog de test retourn 1 : echec de la pipeline
#Ici on fait le makefile de notre projet
build-job:
  stage: build
  script:
    - echo "build"

test-indexation:
  stage: test
  script:
    #- make projet-pfr
    # - gcc testsCI/indexation.c -o testsCI/tests.out
    - cd testsCI
    - make indexationSon
    - ./indexationSon.out
    - rm -f *.o *.out
    - make indexationImage
    - ./indexationImage.out
    - rm -f *.o *.out

test-recherche:
  stage: test
  script:
    #- make projet-pfr
    - cd testsCI
    - make recherche
    - ./recherche.out
    - rm -f *.o *.out

test-progPrincipal:
  stage: test
  script:
    #- make projet-pfr
    - gcc testsCI/progP.c -o testsCI/tests.out
    - ./testsCI/tests.out

