#Ici on fait le makefile de notre projet
build-job:
  stage: build
  script:
    - echo "build"

test-indexation:
  stage: test
  script:
    #- make projet-pfr
    - gcc testsCI/indexation.c -o tests/tests.out
    - ./tests/tests.out

test-recherche:
  stage: test
  script:
    #- make projet-pfr
    - gcc testsCI/recherche.c -o tests/tests.out
    - ./tests/tests.out

test-progPrincipal:
  stage: test
  script:
    #- make projet-pfr
    - gcc testsCI/progP.c -o tests/tests.out
    - ./tests/tests.out

