#Ici on fait le makefile de notre projet
build-job:
  stage: build
  script:
    - echo "build"
#Ici on compile et on execute notre/nos fichier(s) de tests
test-job1:
  stage: test
  script:
    - gcc tests/CItests.c -o tests/tests.out
    - ./tests/tests.out
#Inutile ici mais montre la possibilité de faire d'autres "jobs" = taches
test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
