test : pile_dynamique.c pile_dynamique.h descripteur.c descripteur.h controle_descripteur.c controle_descripteur.h
	gcc -c -Wall pile_dynamique.c -lm
	gcc -c -Wall descripteur.c -lm
	gcc -c -Wall controle_descripteur.c -lm
	gcc -o test.out pile_dynamique.o controle_descripteur.o descripteur.o
